# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Amazing Store - backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    env:
      working-directory: ./ex_8/store/frontend

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_799406ec48634e72ab3bfc10ec776c90 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f6e328bc536e4d5ca42b74c7d3476c65 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_799406ec48634e72ab3bfc10ec776c90 }}/mikolajmgt/amazing-store-backend:${{ github.sha }}
        file: ${{env.working-directory}}/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'amazing-store-backend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b11b308ff71e4f75ac72a8052a69d3b2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_799406ec48634e72ab3bfc10ec776c90 }}/mikolajmgt/amazing-store-backend:${{ github.sha }}'
